# Generated by Django 4.0.5 on 2022-06-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.BigIntegerField()),
                ('gname', models.CharField(max_length=450)),
            ],
        ),
        migrations.AddConstraint(
            model_name='gname',
            constraint=models.UniqueConstraint(fields=('eventid', 'gname'), name='unique_eventid_gname_combination'),
        ),
    ]
